/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DefenceSystem;

/**
 *
 * @author theekshanasankalpa
 */
public class Helicopter extends javax.swing.JFrame implements DefenceSystemObserver{

    /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        initComponents();
        setTitle("Helicopter");
        setLocation(20,30);
    }
    public Helicopter(Object object){
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAction = new javax.swing.JLabel();
        sliderHelicopter = new javax.swing.JSlider();
        spinnerSoldier = new javax.swing.JSpinner();
        spinnerAmmo = new javax.swing.JSpinner();
        checkboxPosition = new javax.swing.JCheckBox();
        btnMissileOperation = new javax.swing.JButton();
        btnShoot = new javax.swing.JButton();
        btnLaserOperation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMainHelicopter = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        txtFieldSend = new javax.swing.JTextField();
        lblAmmoCount = new javax.swing.JLabel();
        lblSoldierCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        sliderHelicopter.setMajorTickSpacing(20);
        sliderHelicopter.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderHelicopter.setPaintLabels(true);
        sliderHelicopter.setPaintTicks(true);
        sliderHelicopter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderHelicopter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderHelicopterStateChanged(evt);
            }
        });

        spinnerSoldier.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        spinnerSoldier.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerSoldierStateChanged(evt);
            }
        });

        checkboxPosition.setText("  Position");
        checkboxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxPositionActionPerformed(evt);
            }
        });

        btnMissileOperation.setText("Missile Operation");
        btnMissileOperation.setAlignmentX(0.5F);
        btnMissileOperation.setMaximumSize(new java.awt.Dimension(78, 25));
        btnMissileOperation.setMinimumSize(new java.awt.Dimension(78, 25));
        btnMissileOperation.setPreferredSize(new java.awt.Dimension(78, 25));
        btnMissileOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileOperationActionPerformed(evt);
            }
        });

        btnShoot.setText("Shoot");
        btnShoot.setAlignmentX(0.5F);
        btnShoot.setMaximumSize(new java.awt.Dimension(78, 25));
        btnShoot.setMinimumSize(new java.awt.Dimension(78, 25));
        btnShoot.setPreferredSize(new java.awt.Dimension(78, 25));
        btnShoot.setSize(new java.awt.Dimension(78, 25));
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        btnLaserOperation.setText("Laser Operation");
        btnLaserOperation.setAlignmentX(0.5F);
        btnLaserOperation.setMaximumSize(new java.awt.Dimension(78, 25));
        btnLaserOperation.setMinimumSize(new java.awt.Dimension(78, 25));
        btnLaserOperation.setPreferredSize(new java.awt.Dimension(78, 25));
        btnLaserOperation.setSize(new java.awt.Dimension(78, 25));
        btnLaserOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaserOperationActionPerformed(evt);
            }
        });

        txtAreaMainHelicopter.setColumns(20);
        txtAreaMainHelicopter.setRows(5);
        jScrollPane1.setViewportView(txtAreaMainHelicopter);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblAmmoCount.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAmmoCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmmoCount.setText("Ammo Count");

        lblSoldierCount.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSoldierCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoldierCount.setText("Soldier Count");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Fuel Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblAction, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLaserOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMissileOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(checkboxPosition))
                            .addComponent(lblAmmoCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSoldierCount, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(spinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldSend, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderHelicopter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderHelicopter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAction, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoldierCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMissileOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(btnShoot, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(lblAmmoCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaserOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldSend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxPositionActionPerformed

    private void btnMissileOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMissileOperationActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnLaserOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaserOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaserOperationActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        MainController mainController = new MainController();
        String message = txtFieldSend.getText();
        MainController.txtAreaMsgBox1.append("\nHelicopter : "+message);
    }//GEN-LAST:event_btnSendActionPerformed

    private void spinnerSoldierStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerSoldierStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spinnerSoldierStateChanged

    private void sliderHelicopterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderHelicopterStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderHelicopterStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helicopter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaserOperation;
    private javax.swing.JButton btnMissileOperation;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JCheckBox checkboxPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblAmmoCount;
    private javax.swing.JLabel lblSoldierCount;
    public static javax.swing.JSlider sliderHelicopter;
    public static volatile javax.swing.JSpinner spinnerAmmo;
    public static javax.swing.JSpinner spinnerSoldier;
    private javax.swing.JTextArea txtAreaMainHelicopter;
    private javax.swing.JTextField txtFieldSend;
    // End of variables declaration//GEN-END:variables

    @Override
    public void areaClearedMessage(boolean status) {
        if (status == true) {
            lblAction.setText("Cleared");
        } else if (status == false) {
            lblAction.setText("Area Not Cleared");
        }
    }
    @Override
    public void updatePosition(int positionLevel) {

        if (checkboxPosition.isSelected() == true) {
            if (positionLevel > 20) {
                btnShoot.setEnabled(true);
            } else {
                btnShoot.setEnabled(false);
            }
            if (positionLevel > 40) {
                btnMissileOperation.setEnabled(true);
            } else {
                btnMissileOperation.setEnabled(false);
            }
            if (positionLevel > 60) {
                btnLaserOperation.setEnabled(true);
            } else {
                btnLaserOperation.setEnabled(false);
            }
        } else {
            btnShoot.setEnabled(false);
            btnMissileOperation.setEnabled(false);
            btnLaserOperation.setEnabled(false);
        }
    }
    @Override
    public void updateSendMessages(String message, boolean select, int checkNum) {

        if (select == true && checkNum == 0) {
            txtAreaMainHelicopter.setText("Private Message : \n\t" + message);
        } else if (select == false) {
            txtAreaMainHelicopter.setText(message);
        }
    }
}
