/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DefenceSystem;

/**
 *
 * @author theekshanasankalpa
 */
public class Submarine extends javax.swing.JFrame implements DefenceSystemObserver{

    /**
     * Creates new form Submarine
     */
    public Submarine() {
        initComponents();
        setTitle("Submarine");
        setLocation(750,30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActionSub = new javax.swing.JLabel();
        lblSoldierCount = new javax.swing.JLabel();
        spinnerSoldier = new javax.swing.JSpinner();
        spinnerAmmoCount = new javax.swing.JSpinner();
        lblAmmoCount = new javax.swing.JLabel();
        btnSonarOperation = new javax.swing.JButton();
        btnShoot = new javax.swing.JButton();
        btnTomahawkMissile = new javax.swing.JButton();
        btnTridentMissile = new javax.swing.JButton();
        checkBoxPosition = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTxtAreaSubmarine = new javax.swing.JTextArea();
        txtFieldSend = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        sliderEnergy = new javax.swing.JSlider();
        sliderOxigen = new javax.swing.JSlider();
        lblEnergy = new javax.swing.JLabel();
        lblOxigen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblSoldierCount.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSoldierCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoldierCount.setText("Soldier Count");

        lblAmmoCount.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAmmoCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmmoCount.setText("Ammo Count");

        btnSonarOperation.setText("Sonar Operation");
        btnSonarOperation.setAlignmentX(0.5F);
        btnSonarOperation.setMaximumSize(new java.awt.Dimension(78, 25));
        btnSonarOperation.setMinimumSize(new java.awt.Dimension(78, 25));
        btnSonarOperation.setPreferredSize(new java.awt.Dimension(78, 25));
        btnSonarOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonarOperationActionPerformed(evt);
            }
        });

        btnShoot.setText("Shoot");
        btnShoot.setAlignmentX(0.5F);
        btnShoot.setMaximumSize(new java.awt.Dimension(78, 25));
        btnShoot.setMinimumSize(new java.awt.Dimension(78, 25));
        btnShoot.setPreferredSize(new java.awt.Dimension(78, 25));
        btnShoot.setSize(new java.awt.Dimension(78, 25));
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        btnTomahawkMissile.setText("Tomahawk Missile");
        btnTomahawkMissile.setAlignmentX(0.5F);
        btnTomahawkMissile.setMaximumSize(new java.awt.Dimension(78, 25));
        btnTomahawkMissile.setMinimumSize(new java.awt.Dimension(78, 25));
        btnTomahawkMissile.setPreferredSize(new java.awt.Dimension(78, 25));
        btnTomahawkMissile.setSize(new java.awt.Dimension(78, 25));
        btnTomahawkMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomahawkMissileActionPerformed(evt);
            }
        });

        btnTridentMissile.setText("Trident-2 Missile");
        btnTridentMissile.setAlignmentX(0.5F);
        btnTridentMissile.setMaximumSize(new java.awt.Dimension(78, 25));
        btnTridentMissile.setMinimumSize(new java.awt.Dimension(78, 25));
        btnTridentMissile.setPreferredSize(new java.awt.Dimension(78, 25));
        btnTridentMissile.setSize(new java.awt.Dimension(78, 25));
        btnTridentMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTridentMissileActionPerformed(evt);
            }
        });

        checkBoxPosition.setText("  Position");
        checkBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPositionActionPerformed(evt);
            }
        });

        mainTxtAreaSubmarine.setColumns(20);
        mainTxtAreaSubmarine.setRows(5);
        jScrollPane1.setViewportView(mainTxtAreaSubmarine);

        txtFieldSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSendActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        sliderEnergy.setMajorTickSpacing(20);
        sliderEnergy.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderEnergy.setPaintLabels(true);
        sliderEnergy.setPaintTicks(true);
        sliderEnergy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sliderOxigen.setMajorTickSpacing(20);
        sliderOxigen.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderOxigen.setPaintLabels(true);
        sliderOxigen.setPaintTicks(true);
        sliderOxigen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblEnergy.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblEnergy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergy.setText("Fuel Amount");

        lblOxigen.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblOxigen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOxigen.setText("Oxigen Level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblActionSub, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTomahawkMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTridentMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSonarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBoxPosition)
                            .addComponent(lblSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(spinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldSend, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sliderOxigen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblOxigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblActionSub, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSonarOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(btnShoot, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(lblAmmoCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTomahawkMissile, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(btnTridentMissile, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldSend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOxigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sliderOxigen, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(sliderEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSonarOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonarOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSonarOperationActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnTomahawkMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomahawkMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTomahawkMissileActionPerformed

    private void btnTridentMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTridentMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTridentMissileActionPerformed

    private void checkBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        String message = txtFieldSend.getText();
        MainController.txtAreaMsgBox1.append("\nSubmarine : "+message);
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtFieldSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonarOperation;
    private javax.swing.JButton btnTomahawkMissile;
    private javax.swing.JButton btnTridentMissile;
    private javax.swing.JCheckBox checkBoxPosition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActionSub;
    private javax.swing.JLabel lblAmmoCount;
    private javax.swing.JLabel lblEnergy;
    private javax.swing.JLabel lblOxigen;
    private javax.swing.JLabel lblSoldierCount;
    private javax.swing.JTextArea mainTxtAreaSubmarine;
    public static javax.swing.JSlider sliderEnergy;
    public static javax.swing.JSlider sliderOxigen;
    public static javax.swing.JSpinner spinnerAmmoCount;
    public static javax.swing.JSpinner spinnerSoldier;
    private javax.swing.JTextField txtFieldSend;
    // End of variables declaration//GEN-END:variables

    public void areaClearedMessage(boolean status) {
        if (status == true) {
            lblActionSub.setText("Cleared");
        } else if (status == false) {
            lblActionSub.setText("Area Not Cleared");
        }
    }
    
    public void updatePosition(int positionLevel) {
        if (checkBoxPosition.isSelected() == true) {
            if (positionLevel > 20) {
                btnShoot.setEnabled(true);
            } else {
                btnShoot.setEnabled(false);
            }
            if (positionLevel > 40) {
                btnSonarOperation.setEnabled(true);
            } else {
                btnSonarOperation.setEnabled(false);
            }
            if (positionLevel > 60) {
                btnTomahawkMissile.setEnabled(true);
            } else {
                btnTomahawkMissile.setEnabled(false);
            }
            if (positionLevel > 80) {
                btnTridentMissile.setEnabled(true);
            } else {
                btnTridentMissile.setEnabled(false);
            }
        } else {
            btnShoot.setEnabled(false);
            btnSonarOperation.setEnabled(false);
            btnTomahawkMissile.setEnabled(false);
            btnTridentMissile.setEnabled(false);
        }
    }

    @Override
    public void updateSendMessages(String message,boolean select,int checkNum) {
        if(select==true && checkNum==2){
        mainTxtAreaSubmarine.setText("Private Message : \n\t"+message);
        }else if(select==false){
        mainTxtAreaSubmarine.setText(message);
        }
    }
}
